import MainProvider from "@/shared/components/providers/MainProvider";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const geistMono = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lien",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistMono.variable} h-full antialiased`}>
      <body>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
